packages:
  - apps/*
  - packages/*
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
resolvePeersFromWorkspaceRoot: false
dedupePeerDependents: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - esbuild
